[package]
name = "beancount-ast-py"
version = '0.0.0'
authors = ["Trim21 <trim21.me@gmail.com>"]
edition = "2024"
homepage = "https://github.com/trim21/beancount-ast"
license = "MIT"
repository = "https://github.com/trim21/beancount-ast"
description = "Python bindings for the beancount-parser directive AST."

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stub_gen"
path = "src/bin/stub_gen.rs"
required-features = ["stub-gen"]

[dependencies]
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "8b4e3311258194fe3127862dd4132028e97cc01d" }
pyderive = "0.9.2"
pyo3 = { version = "0.27.2", features = ["abi3-py310", "multiple-pymethods"] }
pyo3-stub-gen = { git = "https://github.com/Jij-Inc/pyo3-stub-gen", rev = "42dfdd813900015f6dbb7946f9a5878ceadb3fa3", optional = true }
pyo3-stub-gen-derive = { git = "https://github.com/Jij-Inc/pyo3-stub-gen", rev = "42dfdd813900015f6dbb7946f9a5878ceadb3fa3", optional = true }

[features]
default = []
stub-gen = ["dep:pyo3-stub-gen"]
