[package]
name = "beancount-ast-py"
version = '0.0.0'
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "a6682bbe95711ef6c1b1aa76117415bf824a320f" }
pyderive = "0.9.2"
pyo3 = { version = "0.28.0", features = ["abi3-py310", "multiple-pymethods", "generate-import-lib"] }

[features]
default = []
