[package]
name = "beancount-ast-py"
version = '0.0.0'
authors = ["Trim21 <trim21.me@gmail.com>"]
edition = "2024"
homepage = "https://github.com/trim21/beancount-ast"
license = "MIT"
repository = "https://github.com/trim21/beancount-ast"
description = "Python bindings for the beancount-parser directive AST."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "59e4ebee321ec657dc04e10e94641f702dc5207f" }
pyderive = "0.9.2"
pyo3 = { version = "0.28.0", features = ["abi3-py310", "multiple-pymethods", "generate-import-lib"] }

[features]
default = []
